/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("StockRequestsObjectPageObjectPage journey");

        opaTest("Navigate to StockRequestsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheStockRequestsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheStockRequestsListGenerated.onTable().iCheckRows();
            When.onTheStockRequestsListGenerated.onTable().iPressRow(0);

            Then.onTheStockRequestsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the number of sections of the Object Page", function (_Given, _When, Then) {
            Then.onTheStockRequestsObjectPageGenerated.iCheckNumberOfSections(4);
        });

        opaTest("Check the FieldGroup::General section of the Object Page", function (_Given, When, Then) {
            When.onTheStockRequestsObjectPageGenerated.iGoToSection({ section: "FieldGroup::General" });
            Then.onTheStockRequestsObjectPageGenerated.iCheckSection({ section: "FieldGroup::General" });
            Then.onTheStockRequestsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "requestNumber" });
            Then.onTheStockRequestsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "product_ID" });
            Then.onTheStockRequestsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "requestingBranch_ID" });
            Then.onTheStockRequestsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "fulfillingBranch_ID" });
            Then.onTheStockRequestsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "quantity" });
            Then.onTheStockRequestsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "requestType" });
            Then.onTheStockRequestsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "status" });
            Then.onTheStockRequestsObjectPageGenerated.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "priority" });
        });

        opaTest("Check the FieldGroup::Approval section of the Object Page", function (_Given, When, Then) {
            When.onTheStockRequestsObjectPageGenerated.iGoToSection({ section: "FieldGroup::Approval" });
            Then.onTheStockRequestsObjectPageGenerated.iCheckSection({ section: "FieldGroup::Approval" });
            Then.onTheStockRequestsObjectPageGenerated.onForm({ section: "FieldGroup::Approval" }).iCheckField({ property: "requestedBy" });
            Then.onTheStockRequestsObjectPageGenerated.onForm({ section: "FieldGroup::Approval" }).iCheckField({ property: "requestedAt" });
            Then.onTheStockRequestsObjectPageGenerated.onForm({ section: "FieldGroup::Approval" }).iCheckField({ property: "approvedBy" });
            Then.onTheStockRequestsObjectPageGenerated.onForm({ section: "FieldGroup::Approval" }).iCheckField({ property: "approvedAt" });
        });

        opaTest("Check the FieldGroup::Pricing section of the Object Page", function (_Given, When, Then) {
            When.onTheStockRequestsObjectPageGenerated.iGoToSection({ section: "FieldGroup::Pricing" });
            Then.onTheStockRequestsObjectPageGenerated.iCheckSection({ section: "FieldGroup::Pricing" });
            Then.onTheStockRequestsObjectPageGenerated.onForm({ section: "FieldGroup::Pricing" }).iCheckField({ property: "estimatedCost" });
            Then.onTheStockRequestsObjectPageGenerated.onForm({ section: "FieldGroup::Pricing" }).iCheckField({ property: "estimatedCostUSD" });
        });

        opaTest("Check the FieldGroup::Notes section of the Object Page", function (_Given, When, Then) {
            When.onTheStockRequestsObjectPageGenerated.iGoToSection({ section: "FieldGroup::Notes" });
            Then.onTheStockRequestsObjectPageGenerated.iCheckSection({ section: "FieldGroup::Notes" });
            Then.onTheStockRequestsObjectPageGenerated.onForm({ section: "FieldGroup::Notes" }).iCheckField({ property: "notes" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});