/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("StockRequestsListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheStockRequestsListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheStockRequestsListGenerated.onFilterBar().iCheckFilterField({ property: "status" });
            Then.onTheStockRequestsListGenerated.onFilterBar().iCheckFilterField({ property: "priority" });
            Then.onTheStockRequestsListGenerated.onFilterBar().iCheckFilterField({ property: "requestType" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheStockRequestsListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheStockRequestsListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheStockRequestsListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onTheStockRequestsListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onTheStockRequestsListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheStockRequestsListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"requestNumber":{"header":"Request #"},"product_ID":{"header":"Product"},"requestingBranch_ID":{"header":"Requesting Branch"},"fulfillingBranch_ID":{"header":"Fulfilling Branch"},"quantity":{"header":"Qty"},"requestType":{"header":"Type"},"status":{"header":"Status"},"priority":{"header":"Priority"},"estimatedCost":{"header":"Cost (EUR)"},"estimatedCostUSD":{"header":"Cost (USD)"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheStockRequestsListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheStockRequestsListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheStockRequestsListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheStockRequestsObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});